export const images = {
  crop: require('../assets/images/crop.jpg'),
  crop_1: require('../assets/images/crop_1.jpg'),
  crop_2: require('../assets/images/crop_2.jpg'),
  crop_3: require('../assets/images/crop_3.jpg'),
  logo_sqr: require('../assets/images/saarthi_logo_squr.png'),
  ram_profile: require('../assets/images/ramshankar.jpg'),
  home_fill: require('../assets/images/home_fill.png'),
  home_unfill: require('../assets/images/home_unfill.png'),
  video_call_fill: require('../assets/images/video_call_fill.png'),
  video_call_unfill: require('../assets/images/video_call_unfill.png'),
  cart_fill: require('../assets/images/cart_fill.png'),
  cart_unfill: require('../assets/images/cart_unfill.png'),
  chevron_left: require('../assets/images/chevron-left.png'),
  updateProfile: require('../assets/images/bank_amc.png'),
  privacyPolicy: require('../assets/images/privacyPolicy.png'),
  termsCondition: require('../assets/images/termsCondition.png'),
  settings: require('../assets/images/settings.png'),
  translate: require('../assets/images/translate.png'),
  help_support: require('../assets/images/customer-support.png'),
  coming_soon: require('../assets/images/comingSoon.png'),
};
