export enum screens {
  Call = 'Call',
  Home = 'Home',
  Splash = 'Splash',
  Profile = 'Profile',
  SignIn = 'SignIn',
  SignUp = 'SignUp',
  BottomTab = 'BottomTab',
  SaarthiMart = 'SaarthiMart',
  CallHome = 'CallHome',
  ForgotPassword = 'ForgotPassword',
  ChangePassword = 'ChangePassword',
  MyWebView = 'MyWebView',
  CourseHome = 'CourseHome',
  CourseCategory = 'CourseCategory',
  PurchasesCourse = 'PurchasesCourse',
  CourseList = 'CourseList',
  CourseDetails = 'CourseDetails',
  PurchasesCourseClasses = 'PurchasesCourseClasses',
  DoubtClass = 'DoubtClass',
  LiveClass = 'LiveClass',
  RecordedClass = 'RecordedClass',
  RecordedClassDetail = 'RecordedClassDetail',
}
