export const strings = {
  saarthi: 'Saarthi',
  welcome_to_saarthi: 'WELCOME TO SAARTHI',
  join_live_session: 'Join Live Seesion',
  joining_call: 'Joining call...',
  dont_have_acc: "Don't have an account? Sign Up",
  forgot_password: 'Forgot password?',
  login_successfully: 'Login successfully',
  log_out: 'Log Out',
  camera: 'Camera',
  gallery: 'Gallery',
  profile_photo: 'Profile Photo',
  update_profile: 'Update Profile',
  settings: 'Settings',
  privacy_policy: 'Privacy Policy',
  terms_n_cond: 'Terms & Conditions',
  help_n_support: 'Help & Support',
  choose_language: 'Choose Language',
  change_password: 'Change Password',
  err_new_password: "New password & confirm password doesn't match",
  password_updt_successfully: 'Password update successfully!',
  new_password: 'New password',
  confirm_password: 'Confirm new password',
  confirm: 'Confirm',
  enter_ur_full_n: 'Enter your full name',
  enter_ur_mb: 'Enter your mobile number',
  enter_ur_full_add: 'Enter your full address',
  enter_ur_email: 'Enter your email Id',
  password: 'Password',
  sign_up: 'Sign Up',
  join: 'Join',
  watch: 'Watch',
  view_pdf: 'View PDF',
  class: 'CLASS',
};
